### ISSUE TITLE
KeyError when using conditional hyperparameters

### ISSUE THREAD

**Issue by douira** [keras-team/keras-tuner#614] opened 2021-09-26 00:26 UTC
**Describe the bug**
When I use `parent_name` and `parent_valus` I always get a `KeyError` when building a model.

```
Invalid model 5/5
Traceback (most recent call last):
  File "/Users/douira/Documents/dev/uni/bachelorarbeit/tf-time-series/venv/lib/python3.8/site-packages/keras_tuner/engine/hypermodel.py", line 127, in build
    model = self.hypermodel.build(hp)
  File "keras-tuner-test.py", line 22, in model_builder
    dense_units1 = hp.Int(
  File "/Users/douira/Documents/dev/uni/bachelorarbeit/tf-time-series/venv/lib/python3.8/site-packages/keras_tuner/engine/hyperparameters.py", line 850, in Int
    return self._retrieve(hp)
  File "/Users/douira/Documents/dev/uni/bachelorarbeit/tf-time-series/venv/lib/python3.8/site-packages/keras_tuner/engine/hyperparameters.py", line 707, in _retrieve
    return self.values[hp.name]
KeyError: 'dense_units1'
```

**To Reproduce**
Use keras-tuner 1.0.4: https://colab.research.google.com/drive/1dlys0Dmpt9hjLkKOP62SfhYnIQmOgVxy?usp=sharing

```python
import keras_tuner as kt
from tensorflow import keras

def model_builder(hp):
    dense_layers = hp.Int("dense_layers", min_value=0, max_value=2, step=1)

    dense_units1 = hp.Int(
        "dense_units1",
        min_value=16,
        max_value=512,
        step=16,
        parent_name="dense_layers",
        parent_values=[1, 2],
    )

    return keras.Sequential()

tuner = kt.RandomSearch(
    model_builder,
    objective="val_accuracy",
    directory="./model_tuning",
    max_trials=1,
)
```

**Expected behavior**
The model should build normally. This worked on keras-tuner 1.0.3. It does not work (this bug happens) on keras-tuner 1.0.4.

**Additional context**
If there is any way of using conditional hyperparameters on keras-tuner while avoiding this bug I'd be interested to hear about it. Otherwise I'll downgrade my version of keras-tuner until this issue is resolved somehow. Thank you for the great work on this project!

**Would you like to help us fix it?**
I don't know why it's happening. Maybe I'm doing something wrong. If this actually is a bug, then looking at what changed between keras-tuner 1.0.3 and 1.0.4 is probably a good idea. (the Google Collab confirms this difference)

**Comment by fzyzcjy** [comment] 2021-11-16 00:27
any updates? I am seeing the same problem...

**Comment by RavindraWiguna** [comment] 2022-03-04 03:13
Me too, i am trying to use conditional scope for dropout layers, so if the hp boolean is true, it then will create hp for dropout rate. but when i am trying to create the tuner, it give key error
![image](https://user-images.githubusercontent.com/77233945/156692358-ac80c0bd-197d-4fd1-bf5e-0fd6574de669.png)

**Comment by AlvaroCavalcante** [comment] 2022-07-26 02:31
Exactly the same problem here, just trying to reduce the search space by adding condition, but facing this issue.

**Comment by Sophonias1** [comment] 2022-08-08 13:47
@haifeng-jin, 
If I have to use conditional scope as you stated in the code example to fix the problem @douira described, for what reason is the parent option included in the hyperparameter deffinition?

**Comment by haifeng-jin** [comment] 2022-08-15 18:56
@Sophonias1 
I wasn't involved in this part of the design. I believe it is a requirement to support the use case of "with conditional_scope", which uses these `parent` args under the hood.

**Comment by gerwim** [comment] 2022-12-13 21:32
@YASIRAQ I downgraded to 1.0.3, which did not have this regression.

**Comment by EzraWolf** [comment] 2022-12-20 19:31
Had to search for 5-6 hours for this answer, except with Hyperband's objective. The downgrade to 1.0.3 was the only thing that worked. Thank you @gerwim

**Comment by haifeng-jin** [comment] 2022-12-21 19:11
Reopened. I am working on this. Will have it fixed in the next release.

**Closed** 2022-12-22 09:40 UTC
Labels: bug

**Comment by YASIRAQ** [comment] 2022-12-22 22:38
> @Sophonias1 I wasn't involved in this part of the design. I believe it is a requirement to support the use case of "with conditional_scope", which uses these `parent` args under the hood.

hello Sir, please can you tell me if there is a solution for this problem ?

**Comment by rchia16** [comment] 2023-02-03 04:36
@YASIRAQ
Testing on v1.2.0 hasn't given me any issues. Maybe give the recent release a go?

@haifeng-jin
Thanks for fixing this bug, love your work.

**Comment by haifeng-jin** [comment] 2023-02-03 04:45
@rchia16 Thanks!

I also confirm that the bug is fixed in 1.2.0.

**Comment by jczhang320** [comment] 2023-07-14 21:48
in version 1.3.5 i encountered the same bug again, please take a look. Im using the KerasTuner BayesianOptimizer on top of it and the attached is related code

with hp.conditional_scope('fc_depth', hp.get('fc_depth')):
  for which_depth in range(fc_depth):
      model.add(layers.Dense(units = hp.Int(f'Dense_Node_{which_depth}', min_value = self.num_category, max_value = self.input_shape * 2, step = neuron_step), 
                      activation = activation_function, name = f'Dense_Layer_{which_depth}'))

**Comment by Greg-Solo** [comment] 2025-04-27 17:06
In version 1.4.7, also the same bug:
```
Trial 5 Complete [00h 00m 30s]
val_loss: nan

Best val_loss So Far: 2.35050892829895
Total elapsed time: 00h 22m 28s
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[19], line 3
      1 # Grid Search Run
----> 3 tuning_history = tuner_grid.search(
      4     X_train, y_train,
      5     epochs=EPOCH,           # fixed
      6     batch_size=BATCH_SIZE,  # fixed
      7     validation_data=(X_val, y_val),
      8     callbacks=[stop_early, keras.callbacks.TensorBoard("./tuning_logs/")],
      9     verbose=1
     10 )

File ~/miniconda3/envs/NLP/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py:225, in BaseTuner.search(self, *fit_args, **fit_kwargs)
    223 while True:
    224     self.pre_create_trial()
--> 225     trial = self.oracle.create_trial(self.tuner_id)
    226     if trial.status == trial_module.TrialStatus.STOPPED:
    227         # Oracle triggered exit.
    228         break

File ~/miniconda3/envs/NLP/lib/python3.12/site-packages/keras_tuner/src/engine/oracle.py:108, in synchronized..wrapped_func(*args, **kwargs)
    106     LOCKS[oracle].acquire()
    107     THREADS[oracle] = thread_name
--> 108 ret_val = func(*args, **kwargs)
    109 if need_acquire:
    110     THREADS[oracle] = None

File ~/miniconda3/envs/NLP/lib/python3.12/site-packages/keras_tuner/src/engine/oracle.py:476, in Oracle.create_trial(self, tuner_id)
    474     values = None
    475 else:
--> 476     response = self.populate_space(trial_id)
    477     status = response["status"]
    478     values = response["values"] if "values" in response else None

File ~/miniconda3/envs/NLP/lib/python3.12/site-packages/keras_tuner/src/tuners/gridsearch.py:192, in GridSearchOracle.populate_space(self, trial_id)
    190 # Create its immediate next combination.
    191 old_values = self.trials[old_trial_id].hyperparameters.values
--> 192 new_values = self._get_next_combination(old_values)
    193 if new_values is None:
    194     continue

File ~/miniconda3/envs/NLP/lib/python3.12/site-packages/keras_tuner/src/tuners/gridsearch.py:303, in GridSearchOracle._get_next_combination(self, values)
    301 # Bump up the hp value if possible and active.
    302 if hps.is_active(hp):
--> 303     value = hps.values[name]
    304     if value != all_values[name][-1]:
    305         index = all_values[name].index(value) + 1

KeyError: 'lstm_units_1'
```
I'm guessing that this is caused by Grid Search looking for a hyperparameter `lstm_unit_1` that was there during the previous trial, but is not defined now since there is only one layer and therefore only `lstm_unit_0` is defined. My current workaround is to define all `lstm_unit_0` to `lstm_unit_2` before the loop, but this inflates the search space and fills it with unnecessary trials where `lstm_unit_1` and `lstm_unit_2` have their values changed when there's only 1 layer.

Here is the problematic code:
```
# Initiation of LSTM Model

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Dense, Input, SpatialDropout1D, Conv1D, Dropout, Bidirectional
from tensorflow.keras.optimizers import Adam

def build_model(hp):
    model = Sequential()

    # Input
    model.add(Input(shape=(EMBEDDING_DIM,)))

    # Embedding Layer (Fixed)
    model.add(embedding_layer)

    # Number of LSTM Layers
    num_lstm_layers = hp.Int("num_lstm_layers", min_value=1, max_value=3, step=1)

    # Adjust units accordingly, return_seq False for last layer
    for layer_index in range(num_lstm_layers):
        # Return sequence if not last layer
        return_seq = ((layer_index + 1) < (num_lstm_layers))

        # Number of LSTM Units
        model.add(
            LSTM(
                units=hp.Choice(f"lstm_units_{layer_index}", values=[5, 25, 100, 500]),
                activation="tanh",
                recurrent_activation="sigmoid",
                return_sequences=return_seq,
            )
        )
    
    # Step for regularization and dropout are skipped for now

    # Output for 16 labels
    n_classes = 16
    model.add(Dense(n_classes, activation="softmax"))

    # Compile, FIXED Optimizer & Learning Rate
    model.compile(
        optimizer=Adam(learning_rate=0.001),
        loss=tf.keras.losses.categorical_crossentropy,
        metrics=[
            "accuracy",
            "precision",
            "recall",
            "f1_score"
        ]
    )

    return model
```

```
# Initiation of Grid Search Tuner

import keras_tuner as kt

tuner_grid = kt.GridSearch(
    build_model,                # building function
    objective="val_loss",       # options: "val_loss" or custom as in kt.Objective("val_recall", direction="max")
    executions_per_trial=1,
    max_retries_per_trial=1,
    max_consecutive_failed_trials=999,  # high to avoid crashes on consecutive fails
    overwrite=True,
    directory="hpt",
    project_name="grid_search"
)

stop_early = keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True)
```

```
# Grid Search Run

tuning_history = tuner_grid.search(
    X_train, y_train,
    epochs=EPOCH,           # fixed
    batch_size=BATCH_SIZE,  # fixed
    validation_data=(X_val, y_val),
    callbacks=[stop_early, keras.callbacks.TensorBoard("./tuning_logs_3/")],
    verbose=1
)
```
