### ISSUE TITLE
How do I reduce the verbosity of logs during the trials?

### ISSUE THREAD

**Issue by sibyjackgrove** [keras-team/keras-tuner#221] opened 2020-01-22 17:56 UTC
Is there any argument that can be passed to `tuner.search() ` to control the logs being produced at the end of each trial (similar to verbose in Keras `model.filt()`). Right now it is printing all the hyperparameters in addition to other information.

**Comment by jaimeperezsanchez** [comment] 2020-01-23 14:21
If you put 'verbose=0' only the hyperparameters and the score of each trial will appear

**Comment by sibyjackgrove** [comment] 2020-01-23 15:15
Yes, I am aware of that. verbose=0 will only suppress the logs from Keras `model.fit()`. Is there any similar argument for Keras-tuner? I want to suppress the hyperparameter logs at each trial.

**Comment by omalleyt12** [comment] 2020-01-23 19:27
@sibyjackgrove Thanks for the issue!

This is currently not possible but it makes sense to me that we should have an option for this.

IMO we should unify on the `verbose` argument (if it is present) to control this. I'll keep this thread updated on the status of the feature

**Comment by sibyjackgrove** [comment] 2020-01-23 19:45
Thank you for the update @omalleyt12 !

**Comment by romanovzky** [comment] 2020-01-27 13:52
I would vouch for this feature as well. Not only the current verbosity is too extensive, it also lacks some information that could be better, for example trial number, execution time until then and of that trial, etc
I also don't seem to understand what "best_step" means to, as it comes as 0 for every trial (both in hyperband and random at least).

**Comment by yogi-dmt** [comment] 2020-01-28 21:37
I believe the output is coming from the on_trial_end() method in base_tuner.py

`self._display.on_trial_end(self.oracle.get_trial(trial.trial_id))`

I remove this and put my own line that prints out what i want.

There are two additional properties i've added to help me personally. A score_history array on the base_tuner (i can plot my progress, see how many iterations there are, if my search has found a new best)

Also a get_init_points() on the bayesian.py oracle so that if i auto calculate init points with space * 3 i can see when my search switches from diversification to bayesian tuning.

**Comment by haifeng-jin** [comment] 2020-02-14 02:19
We will need this `verbose` argument in AutoKeras, too.
It will be based on this feature on Keras Tuner.

**Comment by Aviously** [comment] 2020-08-17 18:52
Specifying `verbose=0` in `tuner.search()` now also suppress the output from Keras Tuner (since https://github.com/keras-team/keras-tuner/pull/312).

**Comment by juliukvi** [comment] 2020-10-17 08:11
> 
> 
> Specifying `verbose=0` in `tuner.search()` now also suppress the output from Keras Tuner (since #312).

Still get wierd format and colored output after each trial.

**Comment by haifeng-jin** [comment] 2021-02-18 20:20
I assume with the latest release of Keras Tuner 1.0.2, the issue is resolved.
I am closing the issue.
Please let me know if it doesn't.

**Closed by haifeng-jin** 2021-02-18 20:20 UTC
Labels: enhancement

**Comment by nicrie** [comment] 2022-03-04 14:38
Using Keras Tuner 1.1.0
```
  File "build-model.py", line 119, in train_log_reg
    tuner.search(X_train, y_train, verbose=0)
TypeError: search() got an unexpected keyword argument 'verbose'
```
From what I read here, version 1.0.2 should have added this parameter, no? Any idea what I'm doing wrong?

**Comment by martiw1** [comment] 2022-04-13 13:08
Setting the parameter verbose=0 in Tuner.search reduces the output to the console, but all of the logs are still created. How can we suppress creation of the large checkpoint.data-* logs that can reach sizes of 1 GB?
